CATEGORY_KEYWORDS = [
  { "keywords": ["bakery"],
    "category" : "bread",
  },
  { "keywords": ["meat", "deli", "seafood"],
    "category" : "meat",
  },
  { "keywords": ["fruit", "vegetables"],
    "category" : "fruit-veg",
  },
  { "keywords": ["baby"],
    "category" : "baby",
  },
  { "keywords": ["canned", "pantry", "breakfast","biscuits","condiments", "confectionary", "gravy", "health"],
    "category" : "pantry",
  },
  { "keywords": ["chilled","dairy, frozen"],
    "category" : "fridge",
  },
]

CATEGORY_IGNORE_WORDS = {
  "all": [
    "imported",
    "thawed",
    "pieces",
    "piece",
    "fresh",
    "organic",
    "and",
    "australian",
    "per",
    "macro",
    "heart smart",
    "woolworths",
    "created with jamie",
    "coles",
  ],
  "bread" : [],
  "meat": [
    "inghams",
  ],
  "baby": [],
  "fruit-veg": [],
  "pantry": [],
  "fridge": [],
}